### ISSUE TITLE
Core contract for private chain 

### ISSUE THREAD

**Issue by ygizhitsa** [Azure/coco-framework#10]
Currently, I'm working on healthcare concept that would require that all contract would expose behavior required by Consortium Leader or Consortium Member. It is not that you could not implement it with the current Ethereum layout, but it is very convoluted and easy to make a mistake. I would suggest to find the way to enable Leader or Member base contract that all other contract will automatically inherit and used by EVM. The setting for the chain's base contract should be done on the leader/member configuration page within azure portal

(Reprint from #56 azure-blockchain-projects)

**Comment by achamayou** [comment]
Coco has been released as CCF now: https://github.com/Microsoft/CCF

Thank you for your patience!
