### ISSUE TITLE
Download

### ISSUE THREAD

**Issue by ammarheidari** [Azure/coco-framework#12]
Hi,
How I can download and use coco?

**Comment by koalalorenzo** [comment]
At the moment the README file says:
`Microsoft plans to open source the Coco Framework code in 2018.`

**Comment by hakandincs** [comment]
Meanwhile, you can read whitepaper. (wait for 2018 Q1)
https://github.com/Azure/coco-framework/blob/master/docs/Coco%20Framework%20whitepaper.pdf

**Comment by dmitry-pavlov** [comment]
Just in case you (like me) would like to watch something while waiting: 
- [Introducing the Coco Framework (YouTube)](https://www.youtube.com/watch?v=8s6JMmGJ-dY)
- [Inside Coco Framework, the Foundation of Blockchain for Enterprise (Channel 9)](https://channel9.msdn.com/Blogs/Seth-Juarez/Inside-Coco-Framework-the-Foundation-of-Blockchain-for-Enterprise-with-Mark-Russinovich)
Anyone could point to any Coco Framework video courses for developers? Please share.

**Comment by dmitry-pavlov** [comment]
Hey @cavanes! Any updates on which Q of 2018 it is going to appear? TIA!

**Comment by xiexin36** [comment]
Hey @cavanes! Any updates on which Q of 2018 it is going to appear? TIA!

**Comment by dmitry-pavlov** [comment]
Video: [An Introduction to Blockchain with Mark Russinovich](https://www.youtube.com/watch?v=cYWal114BOw) - Microsoft Build, May 7-9, 2018 // Seattle, WA // published on May 9, 2018

**Comment by ChiaraSammarco** [comment]
Hi Everybody!
Do you have any news about the Coco framework? 
Is it available for download now? 
Thanks in advance for all the information you will be able to give me!

**Comment by WaterSh** [comment]
I guess they will make Coco open in Q4 2018.

**Comment by dmitry-pavlov** [comment]
Maybe it's time for .NET community to develop a .NET blockchain framework ourselves as a community driven open source project. Microsoft doesn't seem to be actively working on that...

**Comment by Belorus** [comment]
> Maybe it's time for .NET community to develop a .NET blockchain framework ourselves as a community driven open source project. Microsoft doesn't seem to be actively working on that...

Hyperledger Sawtooth lets you write chaincode in any language (including C#), and exposes state via REST API (easily can be consumed via C#)

**Comment by achamayou** [comment]
Coco has been released as CCF now: https://github.com/Microsoft/CCF

Thank you for your patience!
