### ISSUE TITLE
What language do you guys use for coco-framework? 

### ISSUE THREAD

**Issue by Jingkun-Hu** [Azure/coco-framework#13]

**Comment by flyingoverclouds** [comment]
C# (.net fw & .net core)

**Comment by Jingkun-Hu** [comment]
@flyingoverclouds That's nice, thanks.

**Comment by koalalorenzo** [comment]
What about Go, Python and JavaScript?

**Comment by moodmosaic** [comment]
What about F#?

**Comment by edwinhos** [comment]
What about COBOL?

**Comment by BenDerPan** [comment]
what about Go and python?

**Comment by jeveloper** [comment]
Love to see GO and/or JavaScript

**Comment by hoangtn1304** [comment]
Nice work. When is the exact date this will be open source? :))

**Comment by ndili561** [comment]
Great job guys!!

**Comment by mcarvalho21** [comment]
I would say JavaScript is key. I thought that the Smart Contracts are based on what the blockchain system supports? For example, what Hyperledger Sawtooth or what Ethereum supports.

**Comment by ogreenz** [comment]
Looking forward to see the coco framework! any expected time this would be released?

**Comment by paul-g** [comment]
What about VBA?

**Comment by achamayou** [comment]
Coco has been released as CCF now: https://github.com/Microsoft/CCF

Thank you for your patience!
