### ISSUE TITLE
what`s the time to open source

### ISSUE THREAD

**Issue by lijinghust** [Azure/coco-framework#14]
rt

**Comment by xiexin36** [comment]
I also want to know??? Any One??

**Comment by dcorking** [comment]
is duplicate if issue #12

**Comment by crpietschmann** [comment]
It hasn't been released yet. I would speculate that we might see something at or near the //Build conference coming up in a couple months. Microsoft likes to announce and release cool stuff around their conferences. Hopefully it'll be soon. :)

**Comment by krzysztofp** [comment]
@crpietschmann one year later - any update?

**Comment by achamayou** [comment]
Coco has been released as CCF now: https://github.com/Microsoft/CCF

Thank you for your patience!
