### ISSUE TITLE
Is there any early adopter program / community for Coco Framework?

### ISSUE THREAD

**Issue by dmitry-pavlov** [Azure/coco-framework#16]
I would love to join if any.

**Comment by moodmosaic** [comment]
Count me in as well.

**Comment by koalalorenzo** [comment]
I think everybody would love to :P

**Comment by jeveloper** [comment]
I'd love to join

**Comment by mcarvalho21** [comment]
ditto

**Comment by triconic** [comment]
Something tells me that we will hear nothing until the Microsoft Build event in May - especially since they just had a big re-organization.

**Comment by jeveloper** [comment]
Weird, @triconic  i haven't heard anything from MS , no mention at all at Build

unless I had missed it.

**Comment by dmitry-pavlov** [comment]
@jeveloper you didn't - it was nothing at Build about Coco Framework. 
So **I am wondering when we will be able to string #BUIDL-ing using Coco Framework** :)

**Comment by jeveloper** [comment]
Ahh

@dmitry-pavlov  Spasibo :)

**Comment by triconic** [comment]
I think we can assume - for near-term purposes - that it's dead at this point. There has been no news in almost a year and the company has been unresponsive. Even if they make a release, other providers have had their solutions out in the open for a long period of time - and it would take a year or more for enough people to dig in and validate their work before it could be trusted adequately.

**Comment by JJK14** [comment]
Thanks for posting this graphic. I did miss this mention in Build 2018.

**Comment by triconic** [comment]
Thanks @moodmosaic !

**Comment by paul-g** [comment]
This is amazing

**Comment by dmitry-pavlov** [comment]
While we are waiting, check the post [Microsoft Introduces Blockchain Based Products](https://www.c-sharpcorner.com/news/microsoft-introduced-blockchain-based-products-starting-with-digital-identity) by [Mahesh Chand](https://twitter.com/mcbeniwal) on Oct 14 2018

**Comment by dmitry-pavlov** [comment]
Silence for almost a year. I guess this is a dead project. Leaving it.
