### ISSUE TITLE
Coco - OS compatability

### ISSUE THREAD

**Issue by Krit1** [Azure/coco-framework#19]
Can we know the list of OS that COCO will be compatible with? I am at presenting working on Hyperledger sawtooth - that can be installed in Ubuntu or AWS and not on Azure. If COCO has to work with sawtooth, then COCO has to be installed on Ubuntu or AWS? Will that be possible?

**Comment by dcorking** [comment]
[Ubuntu and other Linux distributions can be installed on Azure.](https://docs.microsoft.com/en-us/azure/virtual-machines/linux/endorsed-distros) Does that help?

As long as machines can talk to each other by IP (for example on different networks - such as a Coco machine on Azure and a Sawtooth machine at Rackspace) then in principle you should be able to write code to integrate different frameworks.

**Comment by achamayou** [comment]
Coco has been released as CCF now: https://github.com/Microsoft/CCF

At the moment, it primarily targets Ubuntu 18.04.

Thank you for your patience!
