### ISSUE TITLE
Any plans to opensource? 

### ISSUE THREAD

**Issue by serganus** [Azure/coco-framework#20]
Hi, I am very interested to try this technology for building our products. Any public/private link to give it a try?

Please provide support: gautam.anand@techchoix.com

**Comment by dcorking** [comment]
It seems the plan to open source didn't work out:
> Microsoft plans to open source the Confidential Consortium Blockchain Framework code in 2018.

https://github.com/Azure/coco-framework/commit/a05fd29fe62cd350a2126bbcad36b400d8be211d#diff-04c6e90faac2675aa89e2176d2eec7d8

**Comment by crpietschmann** [comment]
Like anything pre-release, they may have decided to go a different direction. It's better to shift to something better than to just keep moving with something that wont work as well. All just speculation though, as I haven't seen anything about the future of Coco either.

**Comment by achamayou** [comment]
Coco has been released as CCF now: https://github.com/Microsoft/CCF
