### ISSUE TITLE
Latest version of whitepaper contains review comments panel

### ISSUE THREAD

**Issue by j-mccloskey** [Azure/coco-framework#5]
See https://github.com/Azure/coco-framework/blob/ba1f76825223857e329c3f4db74ffec90146cc11/docs/Coco%20Framework%20whitepaper.pdf

**Comment by Neurone** [comment]
> Commented [SB1]: Will we need approval from Gartner to include in this paper? This is from public-facing description before pay gate.
> Commented [CA2R1]: I am checking with our CELA team.
> DELETED FOR NOW…

Guys, please... :D :D :D
